# HTCondor submit description file
# Everything with a leading # is a comment

universe                = docker
docker_image            = docker.lsv.uni-saarland.de:443/ieltayeb/drug-discovery:1.53
initialdir              = /data/users/isiddig/drug-discovery/project-code
executable              = /data/users/isiddig/drug-discovery/project-code/pre_train_zinc.sh
output                  = /data/users/isiddig/drug-discovery/logs/pre-train-zinc/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).out
error                   = /data/users/isiddig/drug-discovery/logs/pre-train-zinc/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).err
log                     = /data/users/isiddig/drug-discovery/logs/pre-train-zinc/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).log
request_CPUs            = 8
request_memory          = 256G
request_GPUs            = 1
#requirements            =  (machine == "slot1@cl18lx.lsv.uni-saarland.de")
queue 1


