# HTCondor submit description file
# Everything with a leading # is a comment

universe                = docker
docker_image            =  docker.lsv.uni-saarland.de:443/ieltayeb/drug-discovery:1.53
initialdir              = /data/users/isiddig/drug-discovery/project-code
executable              = /data/users/isiddig/drug-discovery/project-code/train_tokenizers.sh
output                  = /data/users/isiddig/drug-discovery/logs/train-tokenizers/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).out
error                   = /data/users/isiddig/drug-discovery/logs/train-tokenizers/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).err
log                     = /data/users/isiddig/drug-discovery/logs/train-tokenizers/run.sh.$(ClusterId).$(Year)_$(Month)_$(Day)_$(SUBMIT_TIME).log
request_CPUs            = 3
request_memory          = 64G
request_GPUs            = 1
#requirements            =  machine == "slot1@cl17lx.lsv.uni-saarland.de"
queue 1


